using EstateHub.Application.Common; using EstateHub.Application.CompanyProjects; using EstateHub.Domain.Enums;
namespace EstateHub.Api.Contracts.CompanyProjects;
public sealed class CompanyProjectDirectoryRequest { public int PageNumber{get;init;}=1; public int PageSize{get;init;}=20; public string? Search{get;init;} public string? Status{get;init;} public string? DeliveryStatus{get;init;} public Guid? LocationId{get;init;} }
public sealed record CompanyProjectRequest(string? Name,string? Slug,string? Description,Guid LocationId,string? DeliveryStatus,DateOnly? ExpectedDeliveryDate,string? RowVersion); public sealed record RowVersionRequest(string? RowVersion);
public sealed record LocationResponse(Guid Id,string Type,string NameEn,string NameAr,string Slug); public sealed record CompanyProjectResponse(Guid Id,string Name,string Slug,string? Description,string DeliveryStatus,DateOnly? ExpectedDeliveryDate,string ProjectStatus,LocationResponse Location,Guid? CoverFileAssetId,int UnitCount,int PublishedListingCount,DateTimeOffset CreatedAt,DateTimeOffset UpdatedAt,string RowVersion){ public static CompanyProjectResponse From(CompanyProjectSummary x)=>new(x.Id,x.Name,x.Slug,x.Description,Text(x.DeliveryStatus),x.ExpectedDeliveryDate,Text(x.ProjectStatus),new(x.Location.Id,Text(x.Location.Type),x.Location.NameEn,x.Location.NameAr,x.Location.Slug),x.CoverFileAssetId,x.UnitCount,x.PublishedListingCount,x.CreatedAt,x.UpdatedAt,Convert.ToBase64String(x.RowVersion)); static string Text(ProjectDeliveryStatus x)=>x switch{ProjectDeliveryStatus.Planned=>"Planned",ProjectDeliveryStatus.UnderConstruction=>"UnderConstruction",ProjectDeliveryStatus.ReadyToMove=>"ReadyToMove",ProjectDeliveryStatus.Delivered=>"Delivered",_=>throw new ArgumentOutOfRangeException()}; static string Text(EstateHub.Domain.Enums.ProjectStatus x)=>x switch{EstateHub.Domain.Enums.ProjectStatus.Draft=>"Draft",EstateHub.Domain.Enums.ProjectStatus.Published=>"Published",EstateHub.Domain.Enums.ProjectStatus.Archived=>"Archived",_=>throw new ArgumentOutOfRangeException()}; static string Text(LocationType x)=>x switch{LocationType.Country=>"Country",LocationType.Governorate=>"Governorate",LocationType.City=>"City",LocationType.District=>"District",_=>throw new ArgumentOutOfRangeException()}; }
public sealed record CompanyProjectsResponse(IReadOnlyList<CompanyProjectResponse> Items,int PageNumber,int PageSize,int TotalCount,int TotalPages,bool HasPreviousPage,bool HasNextPage){public static CompanyProjectsResponse From(PagedResult<CompanyProjectSummary> x)=>new(x.Items.Select(CompanyProjectResponse.From).ToList(),x.PageNumber,x.PageSize,x.TotalCount,x.TotalPages,x.HasPreviousPage,x.HasNextPage);}
public sealed record CompanyProjectManagementAmenityResponse(Guid Id,string Code,string NameEn,string NameAr,string? IconKey,string Scope,bool IsActive){public static CompanyProjectManagementAmenityResponse From(CompanyProjectManagementAmenity x)=>new(x.Id,x.Code,x.NameEn,x.NameAr,x.IconKey,x.Scope switch{AmenityScope.Project=>"Project",AmenityScope.Unit=>"Unit",AmenityScope.Both=>"Both",_=>throw new ArgumentOutOfRangeException()},x.IsActive);}
public sealed record CompanyProjectManagementDetailsResponse(Guid Id,string Name,string Slug,string? Description,string DeliveryStatus,DateOnly? ExpectedDeliveryDate,string ProjectStatus,LocationResponse Location,Guid? CoverFileAssetId,int UnitCount,int PublishedListingCount,DateTimeOffset CreatedAt,DateTimeOffset UpdatedAt,string RowVersion,IReadOnlyList<CompanyProjectManagementAmenityResponse> Amenities,IReadOnlyList<ProjectMediaReplacementItemResponse> Media,IReadOnlyList<ProjectNearbyPlaceResponse> NearbyPlaces){public static CompanyProjectManagementDetailsResponse From(CompanyProjectManagementDetails x){var h=CompanyProjectResponse.From(x.Header);return new(h.Id,h.Name,h.Slug,h.Description,h.DeliveryStatus,h.ExpectedDeliveryDate,h.ProjectStatus,h.Location,h.CoverFileAssetId,h.UnitCount,h.PublishedListingCount,h.CreatedAt,h.UpdatedAt,h.RowVersion,x.Amenities.Select(CompanyProjectManagementAmenityResponse.From).ToList(),x.Media.Select(ProjectMediaReplacementItemResponse.From).ToList(),x.NearbyPlaces.Select(p=>new ProjectNearbyPlaceResponse(p.Id,p.Category,p.Name,p.DistanceMeters,p.TravelMinutes,p.Latitude,p.Longitude)).ToList());}}
public sealed record ReplaceProjectAmenitiesRequest(string? RowVersion,IReadOnlyList<Guid>? AmenityIds);
public sealed record ProjectMediaRequest(Guid FileAssetId,int SortOrder,bool IsCover,string? Caption);
public sealed record ReplaceProjectMediaRequest(string? RowVersion,IReadOnlyList<ProjectMediaRequest>? Items);
public sealed record ProjectAmenityResponse(Guid Id,string Code,string NameEn,string NameAr,string? IconKey,string Scope){public static ProjectAmenityResponse From(CompanyProjectAmenity x)=>new(x.Id,x.Code,x.NameEn,x.NameAr,x.IconKey,x.Scope switch{AmenityScope.Project=>"Project",AmenityScope.Unit=>"Unit",AmenityScope.Both=>"Both",_=>throw new ArgumentOutOfRangeException()});}
public sealed record ProjectMediaReplacementItemResponse(Guid FileAssetId,int SortOrder,bool IsCover,string? Caption){public static ProjectMediaReplacementItemResponse From(CompanyProjectMedia x)=>new(x.FileAssetId,x.SortOrder,x.IsCover,x.Caption);}
public sealed record ReplaceProjectAmenitiesResponse(string RowVersion,IReadOnlyList<ProjectAmenityResponse> Amenities);
public sealed record ReplaceProjectMediaResponse(string RowVersion,IReadOnlyList<ProjectMediaReplacementItemResponse> Items);
public sealed record ProjectNearbyPlaceRequest(string? RowVersion,string? Category,string? Name,decimal? DistanceMeters,int? TravelMinutes,decimal? Latitude,decimal? Longitude);
public sealed record ProjectNearbyPlaceResponse(Guid Id,string Category,string Name,decimal? DistanceMeters,int? TravelMinutes,decimal? Latitude,decimal? Longitude){public static ProjectNearbyPlaceResponse From(CompanyProjectNearbyPlace x)=>new(x.Id,x.Category,x.Name,x.DistanceMeters,x.TravelMinutes,x.Latitude,x.Longitude);}
public sealed record ProjectNearbyPlaceMutationResponse(string RowVersion,ProjectNearbyPlaceResponse NearbyPlace);
