using EstateHub.Application.Common; using EstateHub.Application.CompanyAccess; using EstateHub.Application.CompanyProjects; using EstateHub.Domain.Entities.Catalog; using EstateHub.Domain.Entities.Companies; using EstateHub.Domain.Enums; using EstateHub.Infrastructure.Persistence; using Microsoft.EntityFrameworkCore;
namespace EstateHub.Infrastructure.CompanyProjects;
public sealed class CompanyProjectManagementService(EstateHubDbContext db,ICompanyAccessService access,TimeProvider clock):ICompanyProjectManagementService {
 async Task<CompanyAccessScope?> Scope(Guid user,string permission,CancellationToken ct){var s=await access.GetAuthorizedScopeAsync(user,permission,ct);return s is not null&&await db.Set<Company>().AsNoTracking().AnyAsync(x=>x.Id==s.CompanyId&&x.CompanyType==CompanyType.Developer,ct)?s:null;}
 IQueryable<CompanyProjectSummary> Query(Guid companyId)=>db.Set<Project>().AsNoTracking().Where(x=>x.DeveloperCompanyId==companyId).Select(x=>new CompanyProjectSummary(x.Id,x.Name,x.Slug,x.Description,x.DeliveryStatus,x.ExpectedDeliveryDate,x.ProjectStatus,new CompanyProjectLocation(x.Location.Id,x.Location.Type,x.Location.NameEn,x.Location.NameAr,x.Location.Slug),x.Media.Where(m=>m.IsCover).Select(m=>(Guid?)m.FileAssetId).FirstOrDefault(),x.Units.Count(),x.Units.SelectMany(u=>u.Listings).Count(l=>l.PublicationStatus==ListingPublicationStatus.Published),x.CreatedAt,x.UpdatedAt,x.RowVersion));
 public async Task<PagedResult<CompanyProjectSummary>?> GetProjectsAsync(Guid u,CompanyProjectQuery q,CancellationToken ct=default){var s=await Scope(u,CompanyPermissionCodes.ProjectsRead,ct);if(s is null)return null;var x=Query(s.CompanyId);if(q.Search!=null)x=x.Where(a=>a.Name.Contains(q.Search)||a.Slug.Contains(q.Search)||(a.Description!=null&&a.Description.Contains(q.Search)));if(q.Status!=null)x=x.Where(a=>a.ProjectStatus==q.Status);if(q.DeliveryStatus!=null)x=x.Where(a=>a.DeliveryStatus==q.DeliveryStatus);if(q.LocationId!=null)x=x.Where(a=>a.Location.Id==q.LocationId);var n=await x.CountAsync(ct);var i=await x.OrderByDescending(a=>a.UpdatedAt).ThenByDescending(a=>a.Id).Skip((q.PageNumber-1)*q.PageSize).Take(q.PageSize).ToListAsync(ct);return new(i,q.PageNumber,q.PageSize,n);}
 public async Task<CompanyProjectSummary?> GetProjectAsync(Guid u,Guid id,CancellationToken ct=default){var s=await Scope(u,CompanyPermissionCodes.ProjectsRead,ct);return s is null?null:await Query(s.CompanyId).SingleOrDefaultAsync(x=>x.Id==id,ct);}
 public Task<CompanyProjectOperationResult>CreateProjectAsync(Guid u,CompanyProjectCommand c,CancellationToken ct=default)=>Save(u,Guid.Empty,c,true,ct); public Task<CompanyProjectOperationResult>UpdateProjectAsync(Guid u,Guid id,CompanyProjectCommand c,CancellationToken ct=default)=>Save(u,id,c,false,ct);
 async Task<CompanyProjectOperationResult> Save(Guid u,Guid id,CompanyProjectCommand c,bool create,CancellationToken ct){var s=await Scope(u,CompanyPermissionCodes.ProjectsManage,ct);if(s is null)return new(CompanyProjectOperationStatus.Conflict);if(!await db.Set<Location>().AsNoTracking().AnyAsync(x=>x.Id==c.LocationId&&x.IsActive,ct))return new(CompanyProjectOperationStatus.InvalidReference);Project? p;if(create){var now=clock.GetUtcNow();p=new(){Id=Guid.NewGuid(),DeveloperCompanyId=s.CompanyId,Name=c.Name,Slug=c.Slug,Description=c.Description,LocationId=c.LocationId,DeliveryStatus=c.DeliveryStatus,ExpectedDeliveryDate=c.ExpectedDeliveryDate,ProjectStatus=ProjectStatus.Draft,CreatedAt=now,UpdatedAt=now};db.Add(p);}else{p=await db.Set<Project>().SingleOrDefaultAsync(x=>x.Id==id&&x.DeveloperCompanyId==s.CompanyId,ct);if(p is null)return new(CompanyProjectOperationStatus.NotFound);if(p.ProjectStatus==ProjectStatus.Archived||(p.ProjectStatus==ProjectStatus.Published&&p.Slug!=c.Slug))return new(CompanyProjectOperationStatus.Conflict);db.Entry(p).Property(x=>x.RowVersion).OriginalValue=c.RowVersion!;p.Name=c.Name;p.Slug=c.Slug;p.Description=c.Description;p.LocationId=c.LocationId;p.DeliveryStatus=c.DeliveryStatus;p.ExpectedDeliveryDate=c.ExpectedDeliveryDate;p.UpdatedAt=clock.GetUtcNow();}try{await db.SaveChangesAsync(ct);return new(CompanyProjectOperationStatus.Succeeded,await Query(s.CompanyId).SingleAsync(x=>x.Id==p.Id,ct));}catch(DbUpdateConcurrencyException){return new(CompanyProjectOperationStatus.Conflict);}catch(DbUpdateException){return new(CompanyProjectOperationStatus.Conflict);}}
 public Task<CompanyProjectOperationStatus> PublishProjectAsync(Guid u,Guid id,byte[] rv,CancellationToken ct=default)=>Transition(u,id,rv,ProjectStatus.Draft,ProjectStatus.Published,ct); public Task<CompanyProjectOperationStatus> ArchiveProjectAsync(Guid u,Guid id,byte[] rv,CancellationToken ct=default)=>Transition(u,id,rv,null,ProjectStatus.Archived,ct);
 async Task<CompanyProjectOperationStatus> Transition(Guid u,Guid id,byte[] rv,ProjectStatus? from,ProjectStatus to,CancellationToken ct){var s=await Scope(u,CompanyPermissionCodes.ProjectsManage,ct);if(s is null)return CompanyProjectOperationStatus.Conflict;var p=await db.Set<Project>().SingleOrDefaultAsync(x=>x.Id==id&&x.DeveloperCompanyId==s.CompanyId,ct);if(p is null)return CompanyProjectOperationStatus.NotFound;if(p.ProjectStatus==to)return CompanyProjectOperationStatus.Succeeded;if((from==null&&p.ProjectStatus==ProjectStatus.Archived)||(from!=null&&p.ProjectStatus!=from))return CompanyProjectOperationStatus.Conflict;db.Entry(p).Property(x=>x.RowVersion).OriginalValue=rv;p.ProjectStatus=to;p.UpdatedAt=clock.GetUtcNow();try{await db.SaveChangesAsync(ct);return CompanyProjectOperationStatus.Succeeded;}catch(DbUpdateException){return CompanyProjectOperationStatus.Conflict;}}
}
